### ISSUE TITLE
No description when you open the lightbox

### ISSUE THREAD

**Issue by hteaemel** [coldfumonkeh/gallerificPlus#1]
When the lightbox is open only the title displays. Is it possible to make both the title and description display?

**Comment by coldfumonkeh** [comment]
@hteaemel - thanks for raising this one.

The library builds an array of images and their associated titles for use in the lightbox overlay template. The description was missing. I have added it back in here (two locations, lines 195 and 199)

https://github.com/coldfumonkeh/gallerificPlus/blob/c30a172c08921bfc8cb6f068554036904e0946d0/js/gallerificPlus.js#L195-L199

Once it was included in the array, the overlay template then needed to obtain it and display beneath the title:

https://github.com/coldfumonkeh/gallerificPlus/blob/c30a172c08921bfc8cb6f068554036904e0946d0/js/gallerificPlus.js#L368
